import React, { Children } from 'react';
import "./globals.css";
import Link from "next/link";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


interface RootLayoutProps extends React.PropsWithChildren<{}>{} 
const RootLayout:React.FC<RootLayoutProps>=({children})=>{

  return(
    <html lang="en">
      <body className="">
        <div>
        <ul className="relative flex-row flex space-x-10 ml-[55%] mt-3 text-green-600 font-bold text-[18px]">
          <li className='hover:text-orange-600 hover:border-b-orange-600 hover:border-b'><Link href={"./"}>Welcome</Link></li>
          <li className='hover:text-orange-600 hover:border-b-orange-600 hover:border-b'><Link href={"/music"}>Music</Link></li>
          <li className='hover:text-orange-600 hover:border-b-orange-600 hover:border-b'><Link href={"/comedy"}>Comedy</Link></li>
          <li className='hover:text-orange-600 hover:border-b-orange-600 hover:border-b'><Link href={"/movies"}>Movies</Link></li>
          <li className='hover:text-orange-600 hover:border-b-orange-600 hover:border-b'><Link href={"/celebrity"}>Celebrity</Link></li>
          <li className='hover:text-orange-600 hover:border-b-orange-600 hover:border-b'><Link href={"/tea"}>Tea</Link></li>

        
        </ul>
      


        </div>
        {children}
      </body>
    </html>
  );
};

export default RootLayoutProps

 


